### ISSUE TITLE
How to use crossOver=False

### ISSUE THREAD

**Issue by bartolsthoorn** [SINGROUP/SOAPLite#3]
1. I would like to obtain separate power spectra for each species to construct a delta chemical kernel.
If I understand correctly, `crossover=False` will calculate the spectrum for a single species, but how is it determined which one? The positions `hpos` are just positions in 3D space right?

2. I noticed in the H2O example (in the README), setting crossover=False gives a `(2,180)` matrix instead of `(2,270)`. The 180 comes from:
```python
terms = 0
for n in range(n_max+1):
    for n_prime in range(n_max+1):
        for l in range(l_max):
            terms += 1
print(terms) # => 180
```
Why does `crossover=True` give 270 coefficients per spectrum?

3. In the documentation, you start with "The SOAP power spectrum at a certain position **r** is defined as", and then immediately continue to use **x**..

**Comment by Aki78** [comment]
Thank you for the report,

1. The species are in the order of the periodic table. Correct, hpos is just a point (x,y,z) in space, or a list of it. 
2. For the 2 species case, there are the list of [90 90 90] elements in this  case, the last one is the cross over spectrum of H and O. For details for the size of the descriptor see section 2.2.3 (last paragraph) in soapDoc.pdf in the main repository.
3.  Thank you for the correction, the documentation is still in beta and will keep being updated.
