### ISSUE TITLE
How to derive the equation of C_{nn'l} in the appendix from Eqn 4

### ISSUE THREAD

**Issue by XinyuuLi** [SINGROUP/SOAPLite#5]
Hi,

It is a very beautiful implementation of SOAP. I am wondering how to get the equations of `c_{nn'l}` in the appendix from the Eqn 4 of soapDoc.pdf. I cannot find this information in both SOAPlite documents and the original paper. It is appreciated if you can add more information about this. Thank you very much.

**Comment by Aki78** [comment]
Hi,
I will upload the full derivation on github with the name SoapCalc.pdf. Note that in the equations don't include the standard deviation in the derivations, but in the implementation you can control the gaussian smear by the  eta=1.0 parameter in the soap function. Thank you for the complement.

**Comment by XinyuuLi** [comment]
@Aki78 Thanks.
