### ISSUE TITLE
Reproducing QUIP SOAP vectors with SOAPLite

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [SINGROUP/SOAPLite#6]
Hello,

I'm the developer of a set of MD site analysis tools ([`sitator`](https://github.com/Linux-cpp-lisp/sitator)) that I'm trying to transition over to Python 3. As part of that I'm looking to get away from QUIP/`quippy` with GAP for computing SOAP vectors. SOAPLite looks promising, and I'd love to use it, but I'm having difficulty reproducing my results from QUIP/GAP.

I took the simplified structure [struct-one-Li.cif.txt](https://github.com/SINGROUP/SOAPLite/files/3266703/struct-one-Li.cif.txt) containing one Li atom whose SOAP vector I want to compute. (The rest of the atoms, for simplicity, were all changed to hydrogens.)

**quippy**
With `quippy`, I calculate the SOAP vector:

```
d = quippy.descriptors.Descriptor("soap cutoff=4.0 cutoff_transition_width=0.5 l_max=6 n_max=6 atom_sigma=0.4 n_Z=1 Z={3} normalize=F")
a_qp = qp.Atoms(structure)
a_qp.set_cutoff(4.0)
a_qp.calc_connect()
soaps = d.calc(a_qp, grad = False)['descriptor']
```

The resulting SOAP vector (length 148):

![image](https://user-images.githubusercontent.com/1473644/59117386-947f3e00-891b-11e9-93e3-33dd50f210db.png)

**SOAPLite**

I use this code:

```
li_mask = structure.get_atomic_numbers() == 3
li_pos = structure.get_positions()[np.where(li_mask)[0][0]]
no_li_struct  = structure[~li_mask]
sigma = 0.4
eta = 1/(2*sigma**2)
soaps = soaplite.get_periodic_soap_locals_gauss(static_struct, np.array([li_pos]), rCut = 4.0, nMax = 6, Lmax = 6, eta = eta, all_atomtypes = [1])
```

The resulting SOAP vector (length 147):

![image](https://user-images.githubusercontent.com/1473644/59117605-2e46eb00-891c-11e9-830c-d6103e7852f4.png)

The calculation for `eta` is taken from `pycsoap` (source code [here](https://pypi.org/project/pycsoap/)); I'm not sure if it's correct but it was the best resource I was able to find for how to translate the `atom_sigma` parameter. 
 
----

How can I reproduce my QUIP results with SOAPLite?

Thanks,
A.M.

**Comment by lauri-codes** [comment]
Hi!

Thank you for contacting us. From a quick glance, it seems that the difference is caused by the different radial basis functions used by quippy and soaplite in the examples (I'm not entirely familiar with quippy, but I think they use the polynomial radial basis set, while you have requested a gaussian radial basis set from soaplite). I will reply to you with a better answer after I run some tests.

**Comment by lauri-codes** [comment]
Hi again,

I installed quippy and tested out a few things things. First of all, I have to mention that SOAPLite has been superceded by [the DScribe-package](https://singroup.github.io/dscribe/), which internally uses SOAPLite but provides a more user-friendly interface. You might want to look into this package.

But back to the problem: it seems that quippy uses a different radial basis function and a different cutoff scheme than SOAPLite/DScribe. This makes comparison very difficult. With a very quick search through the [quippy documentation](https://libatoms.github.io/QUIP/descriptors.html), I could not find what kind of formulation of SOAP they are using so I cannot comment much on that. You may want to ask the developers directly.

However, I can say that SOAPLite/DScribe uses the definition given at the documentation page that is found [here](https://singroup.github.io/dscribe/tutorials/soap.html), and more information can be found in the [related manuscript](https://arxiv.org/abs/1904.08875). In short we use real (tesseral) spherical harmonics, and provide two options for the radial basis set: the original polynomial and a computationally more efficient gaussian type orbital-basis. I would argue that options have been tested quite well (you can find tests against a naive python implementation [here](https://github.com/SINGROUP/dscribe/blob/master/regtests/soap.py)).

From a practical point of view, although the output of quippy and SOAPLite differ, it should not matter too much as long as they both use basis functions that are orthonormalized. Thus in practise, I don't see any problem in transitioning to SOAPLite/DScribe as long as you are aware that the output is not identical, but the contained information is very similar. Colleagues and coauthors of this package have done some testing of SOAPLite vs. quippy (you can find some details of this in the supplementary material of [this article](https://www.nature.com/articles/s41524-018-0096-5)).

What seems a bit odd is that the quippy output has 148 elements as opposed to 147. From testing a few cases, it seems that the last element in the quippy output seems to be always zero? Simply by calculating the possible combinations one should in my opinion end up with:  (lmax + 1) * nmax * (nmax + 1)/2 * nelems * (nelems + 1)/2) = 147 with lmax=6, nmax=6, nelems=1. Also, it seems that quippy has trouble with calculating the output for a center overlapping with an atom (theoretically this should not be a problem, and SOAPLite can do it). The problem can be demonstrated for example by this code:

```python
import quippy as qp
from ase import Atoms

structure = Atoms(
    cell=[5, 5, 5],
    positions=[[0, 0, 0], [0.0, 0, 0]],
    symbols=["Li", "H"],
    pbc=False
)
d = qp.descriptors.Descriptor("soap cutoff=4.0 cutoff_transition_width=0.5 l_max=6 n_max=6 atom_sigma=0.4 n_Z=1 Z={3} normalize=F central_reference_all_species=T")
a_qp = qp.Atoms(structure)
a_qp.set_cutoff(4.0)
a_qp.calc_connect()
soaps = d.calc(a_qp, grad=False)['descriptor']

print(soaps)
>>> [[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan   0.]]
```
(Notice that the last element is once again zero, while other are undefined).

**Comment by Linux-cpp-lisp** [comment]
Hi @lauri-codes,

Thanks so much for this quick and comprehensive response.

This makes sense; the following is from SOAPLite with the polynomial basis and it looks "peakier," like the QUIP basis. It looks almost as if QUIP has some component-by-component rescaling. Certainly the basis elements are in a different order, but that doesn't matter. 

![image](https://user-images.githubusercontent.com/1473644/59230887-f5717500-8bac-11e9-8886-767a008402b2.png)

I've implemented `DScribe` in my code; with the Gaussian SOAPs the results (I'm doing clustering over SOAP vectors) do differ meaningfully, but I'll try with polynomial and see if I can reproduce the clusterings I get with QUIP SOAP vectors.

(There's nothing necessarily wrong with the clustering I'm getting with the Gaussian -- they might be an improvement, actually -- but I want to understand what's going on rather than accepting it blindly.)

Thanks for your help!

Best,
A.M.

**Comment by lauri-codes** [comment]
Hi,

Nice that we could be of help! Yes, it definitely makes sense to check the results with the different SOAP implementations, keep us updated if you run into any problems. I think that `sitator` is a great concept and provides a very nice use case of  SOAP.
