### ISSUE TITLE
How to get soap from cif file?

### ISSUE THREAD

**Issue by hori1537** [SINGROUP/SOAPLite#7]
I have the cif file database for machine learning.
I want to get soap discriptors from these cif files.

Is it possible by SOAPlite?

**Comment by lauri-codes** [comment]
Hi!

This is certainly possible. You can use the [ase-library](https://wiki.fysik.dtu.dk/ase/ase/atoms.html) to load many kinds of atomic structures into SOAPLite. This can be done e.g. like this:

```python
import soaplite
import ase.io

structure = ase.io.read("hydrogen.cif")
pos = [[0, 0, 0]]
rcut = 4
nmax = 6
alphas, betas = soaplite.genBasis.getBasisFunc(rcut, nmax)
out = soaplite.get_soap_locals(
    structure,
    pos,
    alp=alphas,
    bet=betas,
    rCut=rcut,
    nMax=nmax,
    Lmax=6,
    eta=1/(2*0.4**2),
    all_atomtypes=[1]
)
```

If you wish, you can also take a look at the [DScribe-library](https://singroup.github.io/dscribe/) that internally uses SOAPLite, but offers maybe a bit easier interface. The same calculation with DScribe could be done with:

 ```python
from dscribe.descriptors import SOAP
import ase.io

structure = ase.io.read("hydrogen.cif")
pos = [[0, 0, 0]]
desc = SOAP(
    species=["H"],
    rcut=4.0,
    nmax=6,
    lmax=6,
    rbf="gto",
    sigma=0.4,
    sparse=False,
    periodic=False
)
out = desc.create(structure, positions=pos)
```
