### ISSUE TITLE
Re:How to get soap from cif file?

### ISSUE THREAD

**Issue by hori1537** [SINGROUP/SOAPLite#8]
Great thanks for #7 "How to get soap from cif file?"

Sorry for a late reply. I tried them about my cif files and read documents, however I can't fully understand yet.

Some of my data are [here](https://github.com/hori1537/for_soap)
I tried the program you answered about ABAVIJ_clean.cif.

I can't understand how to change the code from 'hydrogen.cif' and the meaning of 
*soaplite
 pos = [[0, 0, 0]] 
 rcut = 4
 nmax = 6

* dscribe
   species=["H"], 

Thanks.

**Comment by lauri-codes** [comment]
Hi @hori1537,

For DScribe we have online documentation that tells the meaning of each input argument. You can find the [documentation for the SOAP-class constructor here](https://singroup.github.io/dscribe/tutorials/soap.html#dscribe.descriptors.soap.SOAP.__init__). In those tutorial pages you can find a lot more information, and [our preprint might also be of use.](https://arxiv.org/abs/1904.08875)

For SOAPLite we don't have such documentation, but the arguments are almost identically named as with DScribe. The only difference is that SOAPLite takes the *pos* argument in the soaplite.get_soap_locals function, whereas DScribe takes the *pos* argument in the [SOAP.create()](https://singroup.github.io/dscribe/tutorials/soap.html#dscribe.descriptors.soap.SOAP.create)-method.

I tested and the following code works with the ABAVIJ_clean.cif file: DScribe
```python
from dscribe.descriptors import SOAP
import ase.io

structure = ase.io.read("ABAVIJ_clean.cif")
pos = [[0, 0, 0]]
desc = SOAP(
    species=["H", "O", "Co", "C", "N"],
    rcut=4.0,
    nmax=6,
    lmax=6,
    rbf="gto",
    sigma=0.4,
    sparse=False,
    periodic=False
)
out = desc.create(structure, positions=pos)
print(out)
```
SOAPLite:
```python
import soaplite
import ase.io

structure = ase.io.read("ABAVIJ_clean.cif")
pos = [[0, 0, 0]]
rcut = 4
nmax = 6
alphas, betas = soaplite.genBasis.getBasisFunc(rcut, nmax)
out = soaplite.get_soap_locals(
    structure,
    pos,
    alp=alphas,
    bet=betas,
    rCut=rcut,
    nMax=nmax,
    Lmax=6,
    eta=1/(2*0.4**2),
    all_atomtypes=[1, 6, 7, 8, 27]
)
print(out)
```

**Comment by hori1537** [comment]
Hi @lauri-codes,

Thank you for answer.
I will try your code soon.

I have another question about "species"
Document said 
"species  :Keeping the number of chemical species as low as possible is preferable."

For example
Material A has ["H", "O", "Co", "C", "N"]
Material B has ["H", "O", "Fe", "C", "N"]
Material C has ["H", "Co", "C", "N"]

Should we choose parameters that encompass everything? "A, B, C, species=["H", "O", "Co", "Fe",  "C", "N"]"
or
choose different species for each material?
A : ["H", "O", "Co", "C", "N"]
B : ["H", "O", "Fe", "C", "N"]
C : ["H", "Co", "C", "N"]

Thanks

**Comment by lauri-codes** [comment]
Hi @hori1537,

Almost always you will want the species to **encompass all the chemical species that are in your whole dataset that you are analyzing with SOAP**, but nothing more (the sentence "Keeping the number of chemical species as low as possible is preferable" means that you don't want to give all chemical species of the periodic table here, but just the ones that are present in your dataset.

This is also mentioned in the documentation (maybe I can try to rephrase it so it is more clear): *"species (iterable) – ...Notice that this is not the atomic numbers that are present for an individual system, but should contain all the elements that are ever going to be encountered when creating the descriptors for a set of systems. Keeping the number of chemical species as low as possible is preferable."*

**Comment by hori1537** [comment]
Many thanks.

I understood the species. Now I'm trying machine learning with soap.
There are no additional questions for now.
